<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GenAiAgent.AI\**" />
    <Compile Remove="GenAiAgent.Core\**" />
    <Compile Remove="GenAiAgent.Infra\**" />
    <EmbeddedResource Remove="GenAiAgent.AI\**" />
    <EmbeddedResource Remove="GenAiAgent.Core\**" />
    <EmbeddedResource Remove="GenAiAgent.Infra\**" />
    <None Remove="GenAiAgent.AI\**" />
    <None Remove="GenAiAgent.Core\**" />
    <None Remove="GenAiAgent.Infra\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Azure.AI.Projects" Version="2.0.1" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.5.0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.5.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.ML" Version="6.0.0-preview.26160.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="GenAiAgent.AI\GenAiAgent.AI.csproj" />
    <ProjectReference Include="GenAiAgent.Core\GenAiAgent.Core.csproj" />
    <ProjectReference Include="GenAiAgent.Infra\GenAiAgent.Infra.csproj" />
  </ItemGroup>

</Project>
